name: Deploy to S3

# Trigger on merges into master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev      # uses the dev environment’s secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies & build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Sync dist/ to S3
        uses: aws-actions/s3-sync@v1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET:      ${{ secrets.S3_BUCKET }}
          AWS_REGION:         ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
